version: '3.8'

services:
  app:
    image: php:8.2-fpm-alpine
    container_name: laravel-php-fpm
    working_dir: /var/www/html
    volumes:
      - ./laravel-project:/var/www/html
    networks:
      - laravel-network
    environment:
      - PHP_INI_SCAN_DIR=/usr/local/etc/php/conf.d:/usr/local/etc/php/custom.d
    command: >
      sh -c "
        docker-php-ext-install pdo pdo_mysql &&
        php-fpm
      "

  nginx:
    image: nginx:alpine
    container_name: laravel-nginx
    ports:
      - "80:80"
    volumes:
      - ./laravel-project:/var/www/html
      - ./default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - laravel-network

networks:
  laravel-network:
    driver: bridge