version: '3.8'

services:
  app:
    build:
      context: .
    image: my-portfolio
    container_name: php-fpm
    volumes:
      - .:/var/www
    expose:
      - "9000"
    depends_on:
      - db

  webserver:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "8080:80"
    volumes:
      - .:/var/www
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app

  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: portfolio
      MYSQL_USER: user
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
